### PR TITLE
Not a real PR

### PR DESCRIPTION
**Pull request by masihyeganeh**
I started implementing CLI based on [Arvan Cloud CLI](https://github.com/arvancloud/cli).
just wanted to ask if I'm going in right direction or not.
API code is mostly generated by swagger, so it's not pretty at all, but the CLI is OK by me.
Please let me know if there is something terribly wrong with the code or not.
It can be compiled and run, but I don't have an Arvan account to test it.

### CODE REVIEW

**Comment by masihyeganeh** [comment]
nvm

**Comment by 3a8r** [comment]
Hi, What happened?

**Comment by masihyeganeh** [comment]
Recent non-technical news about the company made me quit working on this and I'm not happy about it.
I hope I could contribute to an open source project in my country but current political news made me hesitate that.
Sorry for wasting your time.

**Comment by 3a8r** [comment]
That's Ok, I hope you read our article about these news.
[ابر ایران و یک شوخی تلخ تکراری با افکار عمومی](https://www.arvancloud.com/blog/%d8%a7%d8%a8%d8%b1-%d8%a7%db%8c%d8%b1%d8%a7%d9%86-%d9%88-%db%8c%da%a9-%d8%b4%d9%88%d8%ae%db%8c-%d8%aa%d9%84%d8%ae-%d8%a8%d8%a7-%d8%a7%d9%81%da%a9%d8%a7%d8%b1%d8%b9%d9%85%d9%88%d9%85%db%8c/)

**Comment by masihyeganeh** [comment]
Ok. I hope it is all misconceptions.
I'm reopening the PR.
It is fully functional, but it can be improved for sure.

**Comment by 3a8r** [comment]
Thanks.
Please look at this. it may be useful for project structure:

[ArvanCloud DNS for ACME](https://github.com/go-acme/lego/tree/master/providers/dns/arvancloud)

**Comment by masihyeganeh** [comment]
Yeah, it has a cleaner http client implementation.
As I said, I used auto generated code for that for the sake of speed and I'm not happy with that too.
I can simplify that if it is OK overall

**Pull request merged**
