### PR TITLE
Latest 

### PR DESCRIPTION
**Pull request by ebihimself**
This PR contains:

1. Scaffolded CMD files
2. E2E working domain CMD
3. E2E implementation of cloud security
4. E2E implementation CDN API 
3. Minimal validators
4. Minimal configuration management for supporting cross-env
5. DNS records factories
6. Implementation of "A" DNS record CLI
7. List, Get, Remove, Toggle, and Info of a DNS record

Next PR will have resolutions to:

1. Creating all DNS record type
2. E2E implementation of CDN (firewall, acceleration and etc)
3. Missing tests

[V1.0.0 milestones](https://github.com/ebrahimahmadi/ar-cli-1/milestones)

### CODE REVIEW

**Comment by ebrahimahmadi** [comment]
@smesgary. Hmm, I see another PR there. Does that mean my PRs will not be accepted?

**Comment by 3a8r** [comment]
Hi, I merged the first acceptable PR, but your PR is also acceptable. The prize will be payed to you too. 
If it is possible please do the contribute on the project and add the missing features on it.

**Comment by ebihimself** [comment]
@smesgary, well I certainly will. But I would prefer to complete the features and make the codebase production-ready In the repo I already made Not this repo. The reason is in case I want to develop missing features I should ignore what I did entirely. So I will continue to make the job done under my repo.

**Comment by 3a8r** [comment]
Hi Ebrahim

If the features are completed and codebase is production ready as you said, please do the PR so we can proceed the payment process.

**Comment by ebihimself** [comment]
Hey, 

The merged branch has different git history with mine, so how are we going to merge the PR?

**Pull request closed without merging**
